# -*- coding: utf-8 -*-
"""Historico de cuadres en PostgreSQL.

Guarda cada ejecucion completa --las lineas de los dos libros, las duplicadas con
su veredicto, los descuadres y los avisos-- para poder consultarlas despues por
rango de fechas y comparar trimestres entre si.

Dos fechas conviven y no significan lo mismo:

  fecha         la de expedicion de la factura
  periodo       el trimestre en cuyo libro se declaro

No coinciden siempre: una factura de marzo puede declararse en el libro del 2T.
Las consultas dejan elegir por cual filtrar.

La conexion se indica con un DSN, en la variable de entorno CUADRE_BD o pasando
`dsn` a cada funcion. Para levantar la base de desarrollo:

    docker compose up -d db
"""
import hashlib
import os
from datetime import datetime

import pandas as pd
from sqlalchemy import create_engine, text

VERSION_ESQUEMA = 2

# OJO con los tipos de los importes: en SQLite REAL son 8 bytes, pero en
# PostgreSQL son 4 y solo guardan unos 6 digitos significativos. Una cuota de
# 2.216.121,79 € se redondearia sola. Aqui van todos en DOUBLE PRECISION.
ESQUEMA = """
CREATE TABLE IF NOT EXISTS meta (
  clave TEXT PRIMARY KEY,
  valor TEXT
);

CREATE TABLE IF NOT EXISTS cargas (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periodo       TEXT NOT NULL,
  ejecutado_en  TEXT NOT NULL,
  fichero_a3    TEXT,
  fichero_bilky TEXT,
  huella_a3     TEXT,
  huella_bilky  TEXT,
  lineas_a3     INTEGER,
  lineas_bilky  INTEGER,
  sociedades    INTEGER,
  cuota_a3      DOUBLE PRECISION,
  cuota_bilky   DOUBLE PRECISION,
  dif_cuota     DOUBLE PRECISION,
  cuadra        INTEGER,
  tasa_regla    DOUBLE PRECISION,
  duplicadas    INTEGER,
  duplicadas_accion INTEGER
);

CREATE TABLE IF NOT EXISTS lineas (
  carga_id   INTEGER NOT NULL REFERENCES cargas(id) ON DELETE CASCADE,
  periodo    TEXT NOT NULL,
  libro      TEXT NOT NULL,
  emp        TEXT,
  sociedad   TEXT,
  fecha      TEXT,
  nif_prov   TEXT,
  proveedor  TEXT,
  num        TEXT,
  num_clave  TEXT,
  tipofra    TEXT,
  tipo       DOUBLE PRECISION,
  base       DOUBLE PRECISION,
  cuota      DOUBLE PRECISION,
  total      DOUBLE PRECISION,
  iddoc      TEXT,
  enlace     TEXT
);

CREATE TABLE IF NOT EXISTS duplicadas (
  carga_id   INTEGER NOT NULL REFERENCES cargas(id) ON DELETE CASCADE,
  periodo    TEXT NOT NULL,
  emp        TEXT, sociedad TEXT,
  nif_prov   TEXT, proveedor TEXT,
  num_a3     TEXT, num_clave TEXT,
  fecha      TEXT, fechas TEXT,
  tipo DOUBLE PRECISION, base DOUBLE PRECISION,
  total DOUBLE PRECISION, cuota DOUBLE PRECISION,
  rep_a3 INTEGER, rep_bilky INTEGER, docs_bilky INTEGER,
  veredicto TEXT, sobrante DOUBLE PRECISION, enlace TEXT
);

CREATE TABLE IF NOT EXISTS descuadres (
  carga_id INTEGER NOT NULL REFERENCES cargas(id) ON DELETE CASCADE,
  periodo  TEXT NOT NULL,
  clase    TEXT NOT NULL,
  emp TEXT, sociedad TEXT,
  nif_prov TEXT, proveedor TEXT,
  num TEXT, fecha TEXT, tipo DOUBLE PRECISION,
  base_a DOUBLE PRECISION, cuota_a DOUBLE PRECISION,
  base_b DOUBLE PRECISION, cuota_b DOUBLE PRECISION,
  dif_cuota DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS avisos (
  carga_id INTEGER NOT NULL REFERENCES cargas(id) ON DELETE CASCADE,
  periodo TEXT NOT NULL, nivel TEXT, texto TEXT
);

CREATE INDEX IF NOT EXISTS ix_lin_fecha    ON lineas(fecha);
CREATE INDEX IF NOT EXISTS ix_lin_periodo  ON lineas(periodo, libro);
CREATE INDEX IF NOT EXISTS ix_lin_emp      ON lineas(emp);
CREATE INDEX IF NOT EXISTS ix_lin_prov     ON lineas(nif_prov);
CREATE INDEX IF NOT EXISTS ix_lin_carga    ON lineas(carga_id);
CREATE INDEX IF NOT EXISTS ix_lin_dup      ON lineas(libro, emp, nif_prov, num_clave, tipo, base);
CREATE INDEX IF NOT EXISTS ix_dup_periodo  ON duplicadas(periodo);
CREATE INDEX IF NOT EXISTS ix_dup_emp      ON duplicadas(emp, veredicto);
CREATE INDEX IF NOT EXISTS ix_des_periodo  ON descuadres(periodo, clase);
CREATE INDEX IF NOT EXISTS ix_des_fecha    ON descuadres(fecha);
"""

DSN_DESARROLLO = "postgresql+psycopg://cuadre:cuadre@localhost:5433/cuadre"

_motores = {}          # dsn -> engine, con el esquema ya creado


def dsn_por_defecto():
    """DSN de la base. Se cambia con la variable de entorno CUADRE_BD."""
    return os.environ.get("CUADRE_BD") or DSN_DESARROLLO


def _normaliza(dsn):
    """Admite el DSN tal cual lo escribe todo el mundo y le pone el driver.

    'postgresql://...' y 'postgres://...' son lo que devuelven los proveedores
    de hosting; SQLAlchemy necesita saber ademas con que driver conectarse.
    """
    dsn = str(dsn or dsn_por_defecto())
    if dsn.startswith("postgres://"):
        dsn = "postgresql://" + dsn[len("postgres://"):]
    if dsn.startswith("postgresql://"):
        dsn = "postgresql+psycopg://" + dsn[len("postgresql://"):]
    return dsn


def motor(dsn=None):
    """Engine de SQLAlchemy, uno por DSN, con el esquema ya asegurado."""
    dsn = _normaliza(dsn)
    if dsn not in _motores:
        eng = create_engine(dsn, pool_pre_ping=True, pool_size=5, max_overflow=5,
                            future=True)
        with eng.begin() as cx:
            cx.execute(text(ESQUEMA))
            cx.execute(text("INSERT INTO meta(clave, valor) VALUES ('version', :v)"
                            " ON CONFLICT (clave) DO NOTHING"), {"v": str(VERSION_ESQUEMA)})
        _motores[dsn] = eng
    return _motores[dsn]


def cierra_motores():
    """Suelta las conexiones. Los tests lo usan entre bases distintas."""
    for eng in _motores.values():
        eng.dispose()
    _motores.clear()


def huella(origen):
    """sha256 de la entrada de un libro, sea una ruta, un buffer, una carpeta o
    una lista de cualquiera de ellos. Sirve para saber si un export ya se cargo.

    Usa la misma normalizacion que el lector, para no interpretar la entrada de
    dos formas distintas en dos sitios distintos.
    """
    from .lectura import entradas

    h = hashlib.sha256()
    for nombre, dato in entradas(origen):
        h.update(str(nombre).encode("utf-8"))
        if hasattr(dato, "read"):
            pos = dato.tell()
            dato.seek(0)
            for trozo in iter(lambda: dato.read(1 << 20), b""):
                h.update(trozo)
            dato.seek(pos)
        else:
            with open(dato, "rb") as f:
                for trozo in iter(lambda: f.read(1 << 20), b""):
                    h.update(trozo)
    return h.hexdigest()


def carga_previa(cx, periodo):
    return cx.execute(text("SELECT id, ejecutado_en FROM cargas WHERE periodo = :p"
                           " ORDER BY id"), {"p": periodo}).fetchall()


# --------------------------------------------------------------------------
# Guardado
# --------------------------------------------------------------------------

def _iso(fecha):
    """dd/mm/aaaa -> aaaa-mm-dd.

    Las fechas se guardan como texto y se filtran comparando texto, asi que
    tienen que estar todas en el mismo formato. Las duplicadas llegan con el
    formato de presentacion, que es el de los informes.
    """
    p = str(fecha).split("/")
    return "%s-%s-%s" % (p[2], p[1], p[0]) if len(p) == 3 else str(fecha)[:10]


def _lineas(df, libro, nombres):
    return pd.DataFrame({
        "libro": libro,
        "emp": df.EMP,
        "sociedad": [nombres.get(e, "") for e in df.EMP],
        "fecha": df.FECHA.dt.strftime("%Y-%m-%d"),
        "nif_prov": df.NIFK,
        "proveedor": df.NOMBRE,
        "num": df.NUM.astype(str),
        "num_clave": df.NUM_CLAVE if "NUM_CLAVE" in df.columns else "",
        "tipofra": df.TIPOFRA,
        "tipo": df.TIPO, "base": df.B2, "cuota": df.C2, "total": df.T2,
        "iddoc": df.IDDOC if "IDDOC" in df.columns else "",
        "enlace": df.LINK if "LINK" in df.columns else "",
    })


def guarda(dsn, periodo, a3, bk, cot, con, dup, avisos, nombres, resumen,
           ficheros=("", ""), huellas=("", ""), reemplaza=True):
    """Escribe una ejecucion completa. Devuelve (carga_id, cargas_reemplazadas)."""
    from . import normaliza as N

    eng = motor(dsn)
    periodo = periodo or "sin periodo"
    with eng.begin() as cx:
        previas = [r[0] for r in carga_previa(cx, periodo)]
        if previas and reemplaza:
            # Las tablas hijas cuelgan de cargas con ON DELETE CASCADE, asi que
            # borrar la carga se lleva por delante sus lineas, duplicadas,
            # descuadres y avisos sin tener que recorrerlas una a una.
            cx.execute(text("DELETE FROM cargas WHERE id = ANY(:ids)"), {"ids": previas})
        elif previas:
            raise ValueError("Ya hay una carga del periodo %s. Usa reemplaza=True." % periodo)

        cid = cx.execute(text(
            "INSERT INTO cargas (periodo, ejecutado_en, fichero_a3, fichero_bilky, huella_a3,"
            " huella_bilky, lineas_a3, lineas_bilky, sociedades, cuota_a3, cuota_bilky,"
            " dif_cuota, cuadra, tasa_regla, duplicadas, duplicadas_accion)"
            " VALUES (:periodo, :ejecutado_en, :fa3, :fbk, :ha3, :hbk, :la3, :lbk, :soc,"
            " :ca3, :cbk, :dif, :cuadra, :tasa, :dup, :dupa) RETURNING id"),
            {"periodo": periodo,
             "ejecutado_en": datetime.now().isoformat(timespec="seconds"),
             "fa3": ficheros[0], "fbk": ficheros[1],
             "ha3": huellas[0], "hbk": huellas[1],
             "la3": len(a3), "lbk": len(bk), "soc": resumen["sociedades"],
             "ca3": resumen["cuota_a3"], "cbk": resumen["cuota_bilky"],
             "dif": con["total"], "cuadra": int(con["cuadra"]),
             "tasa": cot.regla["tasa"], "dup": dup["meta"]["fras"],
             "dupa": dup["meta"]["accion_fras"]}).scalar_one()

        a = a3.copy(); a["NUM_CLAVE"] = a.NUM.map(N.clave)
        b = bk.copy(); b["NUM_CLAVE"] = b.NUM.map(N.clave_bilky)
        L = pd.concat([_lineas(a, "A3", nombres), _lineas(b, "BILKY", nombres)],
                      ignore_index=True)
        L.insert(0, "periodo", periodo)
        L.insert(0, "carga_id", cid)
        _vuelca(L, "lineas", cx)

        if dup["facturas"]:
            D = pd.DataFrame([{
                "carga_id": cid, "periodo": periodo, "emp": f["emp"],
                "sociedad": nombres.get(f["emp"], f["empresa"]), "nif_prov": f["nifp"],
                "proveedor": f["prov"], "num_a3": f["num_a3"],
                "num_clave": N.clave(f["num_a3"]),
                # fecha en ISO para poder filtrar; fechas, en el formato de los
                # informes, porque es lo que se lee.
                "fecha": _iso(f["lineas"][0]["fecha"]), "fechas": " | ".join(f["fechas"]),
                "tipo": f["tipo"], "base": f["base"], "total": f["total"], "cuota": f["cuota"],
                "rep_a3": f["rep_a3"], "rep_bilky": f["rep_bilky"],
                "docs_bilky": f["docs_bilky"], "veredicto": f["v"], "sobrante": f["sobrante"],
                "enlace": f["links"][0]["url"] if f["links"] else ""} for f in dup["facturas"]])
            _vuelca(D, "duplicadas", cx)

        trozos = []
        for clase, d, lado in (("solo_a3", cot.solo_a, "a"), ("solo_bilky", cot.solo_b, "b"),
                               ("importe", cot.dif_comunes, None)):
            if not len(d):
                continue
            c = lado or "a"
            trozos.append(pd.DataFrame({
                "carga_id": cid, "periodo": periodo, "clase": clase, "emp": d.EMP,
                "sociedad": [nombres.get(e, "") for e in d.EMP],
                "nif_prov": d.NIFK, "proveedor": d["nom_" + c],
                "num": d["num_" + c].astype(str),
                "fecha": d["fec_" + c].dt.strftime("%Y-%m-%d"), "tipo": d.TIPO,
                "base_a": d.base_a.round(2), "cuota_a": d.cuota_a.round(2),
                "base_b": d.base_b.round(2), "cuota_b": d.cuota_b.round(2),
                "dif_cuota": d.d_cuota}))
        if trozos:
            _vuelca(pd.concat(trozos, ignore_index=True), "descuadres", cx)

        if avisos:
            _vuelca(pd.DataFrame([{"carga_id": cid, "periodo": periodo, "nivel": a["nivel"],
                                   "texto": a["texto"]} for a in avisos]), "avisos", cx)

    return cid, previas


def _vuelca(df, tabla, cx):
    """Inserta un DataFrame. Un trimestre son ~68.000 lineas: va por lotes."""
    df.to_sql(tabla, cx, if_exists="append", index=False, method="multi", chunksize=1000)


# --------------------------------------------------------------------------
# Consulta
# --------------------------------------------------------------------------

def _lee(sql, dsn, params=None):
    with motor(dsn).connect() as cx:
        return pd.read_sql_query(text(sql), cx, params=params or {})


def _en(campo, valores, params, prefijo):
    """Clausula IN con parametros con nombre, que es lo que admite SQLAlchemy."""
    claves = []
    for i, v in enumerate(valores):
        k = "%s%d" % (prefijo, i)
        params[k] = v
        claves.append(":" + k)
    return " AND %s IN (%s)" % (campo, ",".join(claves))


def cargas(dsn=None):
    return _lee("SELECT * FROM cargas ORDER BY periodo", dsn)


def periodos(dsn=None):
    with motor(dsn).connect() as cx:
        return [r[0] for r in cx.execute(text("SELECT periodo FROM cargas ORDER BY periodo"))]


def rango_fechas(dsn=None):
    with motor(dsn).connect() as cx:
        return tuple(cx.execute(text("SELECT MIN(fecha), MAX(fecha) FROM lineas")).fetchone())


def _filtra(sql, params, desde, hasta, campo_fecha, libro, emps, provs, periodos_):
    if desde:
        sql += " AND %s >= :desde" % campo_fecha
        params["desde"] = str(desde)
    if hasta:
        sql += " AND %s <= :hasta" % campo_fecha
        params["hasta"] = str(hasta)
    if libro and libro != "Ambos":
        sql += " AND libro = :libro"
        params["libro"] = libro
    if emps:
        sql += _en("emp", list(emps), params, "emp")
    if provs:
        sql += _en("nif_prov", list(provs), params, "prov")
    if periodos_:
        sql += _en("periodo", list(periodos_), params, "per")
    return sql, params


def lineas(dsn=None, desde=None, hasta=None, por="fecha", libro=None,
           emps=None, provs=None, periodos_=None, limite=None):
    """Lineas de los dos libros filtradas por rango.

    por='fecha'   filtra por fecha de expedicion de la factura
    por='periodo' filtra por el trimestre en cuyo libro se declaro
    """
    sql = "SELECT * FROM lineas WHERE 1=1"
    params = {}
    if por == "periodo":
        sql, params = _filtra(sql, params, None, None, "fecha", libro, emps, provs, periodos_)
    else:
        sql, params = _filtra(sql, params, desde, hasta, "fecha", libro, emps, provs, periodos_)
    # El orden pone juntas las dos caras de la misma factura, que es lo que se
    # quiere comparar. La clave es num_clave: A3 guarda el numero truncado y
    # Bilky el entero --N020830442 contra P25CON020830442-- pero al normalizar
    # los dos dan lo mismo, asi que agrupa lo que el numero suelto separaria.
    #
    # Luego A3 antes que Bilky, que sale solo del alfabeto ('A3' < 'BILKY'), y
    # los tipos de IVA de menor a mayor: 4, 10, 21.
    #
    # La fecha va primero para no perder el orden cronologico. Separa las 32
    # facturas de 21.411 que tienen fecha distinta en cada libro, y esas son
    # precisamente las que conviene mirar.
    sql += " ORDER BY fecha, emp, nif_prov, num_clave, libro, tipo"
    if limite:
        sql += " LIMIT %d" % int(limite)
    return _lee(sql, dsn, params)


def duplicadas(dsn=None, desde=None, hasta=None, veredictos=None, periodos_=None, emps=None):
    sql = "SELECT * FROM duplicadas WHERE 1=1"
    params = {}
    if desde:
        sql += " AND fecha >= :desde"; params["desde"] = str(desde)
    if hasta:
        sql += " AND fecha <= :hasta"; params["hasta"] = str(hasta)
    if veredictos:
        sql += _en("veredicto", list(veredictos), params, "ver")
    if periodos_:
        sql += _en("periodo", list(periodos_), params, "per")
    if emps:
        sql += _en("emp", list(emps), params, "emp")
    # El desempate no es cosmetico: sin el, dos filas del mismo importe salen en
    # el orden que le apetezca a PostgreSQL y cambia entre consultas. Al ordenar
    # por sociedad en la pantalla --que es estable-- eso desharia la agrupacion.
    sql += " ORDER BY ABS(sobrante) DESC, emp, nif_prov, num_clave"
    return _lee(sql, dsn, params)


def descuadres(dsn=None, desde=None, hasta=None, clases=None, periodos_=None, emps=None):
    sql = "SELECT * FROM descuadres WHERE 1=1"
    params = {}
    if desde:
        sql += " AND fecha >= :desde"; params["desde"] = str(desde)
    if hasta:
        sql += " AND fecha <= :hasta"; params["hasta"] = str(hasta)
    if clases:
        sql += _en("clase", list(clases), params, "cla")
    if periodos_:
        sql += _en("periodo", list(periodos_), params, "per")
    if emps:
        sql += _en("emp", list(emps), params, "emp")
    sql += " ORDER BY ABS(dif_cuota) DESC, emp, nif_prov, num"
    return _lee(sql, dsn, params)


def resumen_por_periodo(dsn=None):
    return _lee(
        "SELECT periodo, ejecutado_en, lineas_a3, lineas_bilky, sociedades,"
        " cuota_a3, cuota_bilky, dif_cuota, cuadra, tasa_regla, duplicadas,"
        " duplicadas_accion FROM cargas ORDER BY periodo", dsn)


def sociedades(dsn=None):
    return _lee(
        "SELECT emp, MAX(sociedad) AS sociedad, COUNT(*) AS lineas"
        " FROM lineas GROUP BY emp ORDER BY emp", dsn)


def duplicadas_entre_periodos(dsn=None, minimo_iva=0.0, limite=None, dias_basura=3):
    """La misma factura declarada en dos trimestres distintos.

    Es el riesgo que solo aparece cuando hay historico: dentro de un trimestre el
    informe ya lo detecta, pero una factura repetida en 1T y en 2T no la ve nadie.

    Se mira en los dos libros y se dice en cual pasa, porque no significan lo
    mismo: en A3 es una deduccion repetida --lo que se declara--, en Bilky es una
    captura repetida que todavia no ha llegado a A3, y en los dos a la vez es lo
    peor, porque entonces el cuadre entre libros no lo delata.

    Se excluyen los numeros que no identifican nada --el mismo «numero» en mas de
    `dias_basura` fechas distintas dentro de un mismo trimestre, como cuando se
    cuela parte de un NIF en el campo--, porque generarian falsos positivos.
    """
    df = _lee("""
        WITH basura AS (
            SELECT emp, nif_prov, num_clave, libro
              FROM lineas
             WHERE num_clave <> ''
             GROUP BY emp, nif_prov, num_clave, libro, periodo
            HAVING COUNT(DISTINCT fecha) > :dias
        )
        SELECT l.libro, l.emp, MAX(l.sociedad) AS sociedad, l.nif_prov,
               MAX(l.proveedor) AS proveedor, l.num_clave, l.tipo, l.base,
               COUNT(DISTINCT l.periodo) AS trimestres,
               STRING_AGG(DISTINCT l.periodo, ', ' ORDER BY l.periodo) AS periodos,
               STRING_AGG(DISTINCT l.fecha, ', ' ORDER BY l.fecha) AS fechas,
               -- El numero tal cual lo guarda el libro. num_clave sirve para
               -- agrupar --es el truncado y normalizado-- pero no se puede
               -- enseñar: nadie encontraria «92026C» buscando en A3.
               STRING_AGG(DISTINCT l.num, ' | ' ORDER BY l.num) AS numeros,
               SUM(l.cuota) AS cuota_total, MAX(l.cuota) AS cuota_una,
               COUNT(*) AS lineas
          FROM lineas l
         WHERE l.num_clave <> '' AND (l.base <> 0 OR l.total <> 0)
           AND NOT EXISTS (SELECT 1 FROM basura b
                            WHERE b.emp = l.emp AND b.nif_prov = l.nif_prov
                              AND b.num_clave = l.num_clave AND b.libro = l.libro)
         GROUP BY l.libro, l.emp, l.nif_prov, l.num_clave, l.tipo, l.base
        HAVING COUNT(DISTINCT l.periodo) > 1
         ORDER BY ABS(SUM(l.cuota) - MAX(l.cuota)) DESC
    """, dsn, {"dias": dias_basura})
    if not len(df):
        return df
    # El campo del numero a veces trae el NIF del proveedor o el de la propia
    # sociedad. Entonces dos facturas distintas del mismo importe --un alquiler
    # mensual, por ejemplo-- pareceria la misma repetida.
    from . import normaliza as N
    es_nif = [nc == N.clave(np_) or nc == N.clave(e)
              for nc, np_, e in zip(df.num_clave, df.nif_prov, df.emp)]
    df = df[~pd.Series(es_nif, index=df.index)]
    if not len(df):
        return df

    # Y la otra fuente de falsos positivos, esta propia de aqui: la regla de
    # truncado. «0049 - 2026/C» y «0079 - 2026/C» son la minuta de mayo y la de
    # julio, dos facturas distintas, pero A3 las deja iguales y parecerian la
    # misma repetida en dos trimestres. Bilky si guarda el numero entero, asi
    # que se le pregunta a el: si detras de esa clave hay mas de un numero real,
    # es una colision y no un duplicado.
    with motor(dsn).connect() as cx:
        choques = {(r[0], r[1], r[2]) for r in cx.execute(text(
            "SELECT emp, nif_prov, num_clave FROM lineas"
            " WHERE libro = 'BILKY' AND num_clave <> ''"
            " GROUP BY emp, nif_prov, num_clave HAVING COUNT(DISTINCT num) > 1"))}
    df["colision"] = [(e, np_, nc) in choques
                      for e, np_, nc in zip(df.emp, df.nif_prov, df.num_clave)]
    df["iva_repetido"] = (df.cuota_total - df.cuota_una).round(2)
    if minimo_iva:
        df = df[df.iva_repetido.abs() >= minimo_iva]
    if limite:
        df = df.head(int(limite))
    return df.reset_index(drop=True)


def numeros_sospechosos(dsn=None, dias_repetido=3, minimo_trozo=6, limite=None):
    """Numeros de factura que no identifican ninguna factura.

    En el informe de un cuadre esto ya sale, pero solo del trimestre que se
    acaba de lanzar. Aqui se mira sobre todo lo archivado, que es donde se ve
    lo importante: el mismo «numero» del mismo proveedor repartido por varias
    sociedades y varios trimestres. `ES20` de ORCONSA en tres sociedades no se
    puede ver desde dentro de un solo cuadre.

    Salta por cinco motivos, y se dice cual:

      nif          el numero es un NIF --del proveedor, de la sociedad, o de
                   otra sociedad vuestra--, con o sin el «ES» delante
      trozo_nif    es un trozo largo del NIF del proveedor: «647451» son los
                   seis ultimos de A28647451
      fecha        el numero es la propia fecha de la factura: «10.02.2026» en
                   una factura del 10/02/2026
      sociedades   el mismo numero del mismo proveedor en varias sociedades
      repetido     el mismo numero en muchos dias distintos

    No hay regla de «numero demasiado corto»: no hace falta y ademas engañaba.
    `num_clave` quita los ceros de la izquierda, asi que «002481» parecia de
    cuatro caracteres. Y un numero corto que no se repite no es un problema; si
    se repite, ya lo cazan los dos criterios de arriba --«ES20» de ORCONSA entra
    por estar en tres sociedades--.
    """
    from . import lectura as LEC
    from . import normaliza as N

    propios = list(LEC.sociedades_propias())
    params = {"dias": int(dias_repetido), "trozo": int(minimo_trozo)}
    ors = ["g.dias >= :dias", "c.sociedades >= 2",
           "g.num_clave = g.k_prov", "g.num_clave = g.k_emp",
           "(LENGTH(g.num_clave) >= :trozo AND POSITION(g.num_clave IN g.k_prov) > 0)",
           "g.es_fecha"]
    if propios:
        claves = []
        for i, p in enumerate(propios):
            params["pr%d" % i] = N.clave(p)
            claves.append(":pr%d" % i)
        ors.append("g.num_clave IN (%s)" % ",".join(claves))

    df = _lee("""
        WITH g AS (
            -- Se agrupa por el numero REAL, no por num_clave. num_clave es el
            -- truncado de A3, y dos facturas distintas pueden compartirlo:
            -- «0092 - 2026/C» y «0002 - 2026/C» quedan las dos en «2 2026 C».
            -- Contando sociedades por la clave, esas colisiones parecerian la
            -- misma factura repartida por varias sociedades.
            SELECT l.libro, l.emp, MAX(l.sociedad) AS sociedad, l.nif_prov,
                   MAX(l.proveedor) AS proveedor, l.num, MAX(l.num_clave) AS num_clave,
                   COUNT(*) AS lineas,
                   COUNT(DISTINCT l.fecha) AS dias,
                   STRING_AGG(DISTINCT l.periodo, ', ' ORDER BY l.periodo) AS periodos,
                   SUM(l.cuota) AS cuota,
                   LTRIM(REGEXP_REPLACE(UPPER(l.nif_prov), '[^A-Z0-9]', '', 'g'), '0') AS k_prov,
                   LTRIM(REGEXP_REPLACE(UPPER(l.emp),      '[^A-Z0-9]', '', 'g'), '0') AS k_emp,
                   -- El numero es la propia fecha de la factura. Se compara ya
                   -- normalizado --num_clave es solo digitos y sin ceros por la
                   -- izquierda--, asi que valen «10.02.2026», «10/02/2026» y el
                   -- «10 02 2026» que deja A3 al convertir los separadores.
                   BOOL_OR(l.fecha ~ '^\\d{4}-\\d{2}-\\d{2}$' AND l.num_clave IN (
                       LTRIM(TO_CHAR(l.fecha::date, 'DDMMYYYY'), '0'),
                       LTRIM(TO_CHAR(l.fecha::date, 'YYYYMMDD'), '0'),
                       LTRIM(TO_CHAR(l.fecha::date, 'DDMMYY'), '0'))) AS es_fecha
              FROM lineas l
             WHERE l.num_clave <> ''
             GROUP BY l.libro, l.emp, l.nif_prov, l.num
        ), c AS (
            SELECT nif_prov, num, COUNT(DISTINCT emp) AS sociedades
              FROM g GROUP BY nif_prov, num
        ), col AS (
            -- Claves que en Bilky esconden mas de un numero real. En A3 esas
            -- facturas quedan con el mismo texto en sociedades distintas y
            -- pareceria la misma repartida; no lo es.
            SELECT nif_prov, num_clave FROM lineas
             WHERE libro = 'BILKY' AND num_clave <> ''
             GROUP BY nif_prov, num_clave HAVING COUNT(DISTINCT num) > 1
        )
        SELECT g.libro, g.emp, g.sociedad, g.nif_prov, g.proveedor, g.num,
               g.num_clave, g.lineas, g.dias, g.periodos, g.cuota,
               g.k_prov, g.k_emp, g.es_fecha, c.sociedades,
               (col.num_clave IS NOT NULL) AS colision
          FROM g JOIN c ON c.nif_prov = g.nif_prov AND c.num = g.num
          LEFT JOIN col ON col.nif_prov = g.nif_prov AND col.num_clave = g.num_clave
         WHERE %s
         ORDER BY c.sociedades DESC, g.lineas DESC
    """ % " OR ".join(ors), dsn, params)
    if not len(df):
        return df

    # El «ES» delante es el codigo de pais del NIF-IVA: ES20 de ORCONSA es su
    # NIF a medio capturar. Se quita antes de comparar.
    sin_es = df.num_clave.str.replace(r"^ES", "", regex=True)
    propios_k = {N.clave(p) for p in propios if N.clave(p)}
    es_nif_prov = (df.num_clave == df.k_prov) | (sin_es == df.k_prov)
    es_nif_emp = (df.num_clave == df.k_emp) | (sin_es == df.k_emp)
    es_nif_propio = (df.num_clave.isin(propios_k) | sin_es.isin(propios_k)) & ~es_nif_emp
    trozo = pd.Series([len(k) >= minimo_trozo and bool(p) and k in p
                       for k, p in zip(df.num_clave, df.k_prov)], index=df.index)

    def motivo(i):
        if df.es_fecha[i]:
            return "es la fecha de la factura"
        if es_nif_emp[i]:
            return "nif de la sociedad"
        if es_nif_propio[i]:
            return "nif de otra sociedad vuestra"
        if es_nif_prov[i]:
            return "nif del proveedor"
        if trozo[i]:
            return "trozo del nif del proveedor"
        if varias[i]:
            return "el mismo en varias sociedades"
        return "se repite muchos dias"

    # «El mismo en varias sociedades» no vale si el numero de A3 viene de un
    # truncado que en Bilky esconde varios: entonces no es el mismo numero.
    varias = (df.sociedades >= 2) & ~df.colision.astype(bool)
    df["motivo"] = [motivo(i) for i in df.index]
    df["es_nif"] = es_nif_prov | es_nif_emp | es_nif_propio | trozo
    # El filtro de la consulta es a proposito mas ancho que estas reglas --en SQL
    # no se puede quitar el «ES» ni comparar contra la lista de sociedades--, asi
    # que aqui se recorta a lo que de verdad cumple alguna.
    df = df[df.es_nif | varias | df.es_fecha.astype(bool)
            | (df.dias >= dias_repetido)]
    df = df.drop(columns=["k_prov", "k_emp"])
    df["cuota"] = df.cuota.round(2)
    if limite:
        df = df.head(int(limite))
    return df.reset_index(drop=True)


def evolucion_duplicadas(dsn=None):
    """Sociedades que repiten duplicadas trimestre tras trimestre."""
    return _lee("""
        SELECT emp, MAX(sociedad) AS sociedad,
               COUNT(DISTINCT periodo) AS trimestres,
               STRING_AGG(DISTINCT periodo, ',') AS periodos,
               COUNT(*) AS facturas,
               ROUND(SUM(sobrante)::numeric, 2) AS iva
          FROM duplicadas
         WHERE veredicto IN ('solo_a3','doc_repetido','sincontraste')
         GROUP BY emp
         ORDER BY trimestres DESC, iva DESC
    """, dsn)


def tamano(dsn=None):
    """Lo que ocupa el historico, ya formateado. Antes era el tamano del fichero."""
    with motor(dsn).connect() as cx:
        return cx.execute(text("SELECT pg_size_pretty(pg_database_size(current_database()))")
                          ).scalar_one()


def borra_periodo(dsn, periodo):
    with motor(dsn).begin() as cx:
        ids = [r[0] for r in cx.execute(text("SELECT id FROM cargas WHERE periodo = :p"),
                                        {"p": periodo})]
        if ids:
            cx.execute(text("DELETE FROM cargas WHERE id = ANY(:ids)"), {"ids": ids})
    return len(ids)
