# -*- coding: utf-8 -*-
"""Usuarios y sesiones.

No hay permisos: quien entra ve todo. La cuenta existe para saber quien hace
cada cosa y para que la aplicacion no quede abierta en internet, no para
repartir capacidades.

La contrasena se guarda con scrypt, que viene en la biblioteca estandar: una
dependencia menos que parchear en el servidor, y es la funcion que recomienda
el propio Python para esto. Nunca se guarda la contrasena, solo su derivada.

De la sesion se guarda el sha256 del testigo, no el testigo. Asi, si alguien se
lleva una copia de la base, no se lleva con ella las sesiones abiertas.
"""
import hashlib
import hmac
import os
import secrets
from datetime import datetime, timedelta, timezone
from sqlalchemy import text
from . import bd

# Coste de scrypt. 2**15 tarda ~100 ms, que es lo que se busca: imperceptible al
# entrar, caro de repetir millones de veces para quien robe la tabla.
N, R, P = 2 ** 15, 8, 1

# scrypt necesita 128*N*r bytes, que con estos parametros son 32 MB justos: el
# tope por defecto de OpenSSL. Sin subirlo revienta con «memory limit exceeded».
MAXMEM = 128 * N * R * 2
DIAS_SESION = int(os.environ.get("CUADRE_DIAS_SESION", "14"))
MIN_CLAVE = 10

ESQUEMA = """
CREATE TABLE IF NOT EXISTS usuarios (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario   TEXT NOT NULL UNIQUE,
  nombre    TEXT NOT NULL,
  clave     TEXT NOT NULL,
  activo    BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  ultimo_acceso TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS sesiones (
  testigo    TEXT PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  creada_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expira_en  TIMESTAMPTZ NOT NULL,
  agente     TEXT
);

CREATE INDEX IF NOT EXISTS ix_ses_usuario ON sesiones(usuario_id);
CREATE INDEX IF NOT EXISTS ix_ses_expira  ON sesiones(expira_en);
"""

_preparado = set()

class ErrorDeUsuario(Exception):
    """Algo que se le puede contar a quien lo esta haciendo."""

def _motor(dsn=None):
    eng = bd.motor(dsn)
    if eng.url not in _preparado:
        with eng.begin() as cx:
            cx.execute(text(ESQUEMA))
        _preparado.add(eng.url)
    return eng

# --------------------------------------------------------------------------
# Contrasenas
# --------------------------------------------------------------------------
def cifra(clave):
    sal = secrets.token_bytes(16)
    dk = hashlib.scrypt(clave.encode("utf-8"), salt=sal, n=N, r=R, p=P, dklen=32,
                        maxmem=MAXMEM)
    return "scrypt$%d$%d$%d$%s$%s" % (N, R, P, sal.hex(), dk.hex())

def verifica(clave, guardada):
    """Comparacion en tiempo constante: una comparacion normal filtra el prefijo."""
    try:
        etiqueta, n, r, p, sal, esperado = guardada.split("$")
        if etiqueta != "scrypt":
            return False
        dk = hashlib.scrypt(clave.encode("utf-8"), salt=bytes.fromhex(sal),
                            n=int(n), r=int(r), p=int(p), dklen=len(esperado) // 2,
                            maxmem=128 * int(n) * int(r) * 2)
    except (ValueError, TypeError):
        return False
    return hmac.compare_digest(dk.hex(), esperado)

def _valida_clave(clave):
    if len(clave or "") < MIN_CLAVE:
        raise ErrorDeUsuario("La contraseña necesita al menos %d caracteres." % MIN_CLAVE)

# --------------------------------------------------------------------------
# Usuarios
# --------------------------------------------------------------------------
def crea(usuario, nombre, clave, dsn=None):
    usuario = (usuario or "").strip().lower()
    if not usuario:
        raise ErrorDeUsuario("Hace falta un nombre de usuario.")
    _valida_clave(clave)
    with _motor(dsn).begin() as cx:
        existe = cx.execute(text("SELECT 1 FROM usuarios WHERE usuario = :u"),
                            {"u": usuario}).first()
        if existe:
            raise ErrorDeUsuario("Ya existe el usuario «%s»." % usuario)
        return cx.execute(text(
            "INSERT INTO usuarios (usuario, nombre, clave) VALUES (:u, :n, :c) RETURNING id"),
            {"u": usuario, "n": (nombre or usuario).strip(), "c": cifra(clave)}).scalar_one()

def cambia_clave(usuario, clave, dsn=None):
    _valida_clave(clave)
    with _motor(dsn).begin() as cx:
        n = cx.execute(text("UPDATE usuarios SET clave = :c WHERE usuario = :u"),
                       {"c": cifra(clave), "u": usuario.strip().lower()}).rowcount
        if not n:
            raise ErrorDeUsuario("No existe el usuario «%s»." % usuario)
        # Cambiar la contrasena cierra las sesiones abiertas: es lo que se espera
        # cuando se cambia porque se cree que alguien la sabe.
        cx.execute(text("DELETE FROM sesiones WHERE usuario_id ="
                        " (SELECT id FROM usuarios WHERE usuario = :u)"),
                   {"u": usuario.strip().lower()})
    return True

def activa(usuario, valor=True, dsn=None):
    with _motor(dsn).begin() as cx:
        n = cx.execute(text("UPDATE usuarios SET activo = :a WHERE usuario = :u"),
                       {"a": bool(valor), "u": usuario.strip().lower()}).rowcount
        if not valor:
            cx.execute(text("DELETE FROM sesiones WHERE usuario_id ="
                            " (SELECT id FROM usuarios WHERE usuario = :u)"),
                       {"u": usuario.strip().lower()})
    return bool(n)

def lista(dsn=None):
    with _motor(dsn).connect() as cx:
        return [dict(r) for r in cx.execute(text(
            "SELECT id, usuario, nombre, activo, creado_en, ultimo_acceso"
            " FROM usuarios ORDER BY usuario")).mappings()]

def hay_alguno(dsn=None):
    with _motor(dsn).connect() as cx:
        return bool(cx.execute(text("SELECT 1 FROM usuarios WHERE activo LIMIT 1")).first())

# --------------------------------------------------------------------------
# Sesiones
# --------------------------------------------------------------------------
def _huella(testigo):
    return hashlib.sha256(testigo.encode("utf-8")).hexdigest()

def entra(usuario, clave, agente=None, dsn=None):
    """Devuelve (testigo, usuario) si la pareja es buena, o (None, None).

    No distingue entre usuario que no existe y contrasena mala: contarlo seria
    decirle a quien prueba cuales de los nombres que ha inventado existen.
    """
    usuario = (usuario or "").strip().lower()
    with _motor(dsn).begin() as cx:
        u = cx.execute(text("SELECT id, usuario, nombre, clave, activo FROM usuarios"
                            " WHERE usuario = :u"), {"u": usuario}).mappings().first()
        if not u or not u["activo"] or not verifica(clave or "", u["clave"]):
            return None, None
        testigo = secrets.token_urlsafe(32)
        cx.execute(text(
            "INSERT INTO sesiones (testigo, usuario_id, expira_en, agente)"
            " VALUES (:t, :uid, :exp, :ag)"),
            {"t": _huella(testigo), "uid": u["id"], "ag": (agente or "")[:300],
             "exp": datetime.now(timezone.utc) + timedelta(days=DIAS_SESION)})
        cx.execute(text("UPDATE usuarios SET ultimo_acceso = now() WHERE id = :id"),
                   {"id": u["id"]})
    return testigo, {"id": u["id"], "usuario": u["usuario"], "nombre": u["nombre"]}

def verifica_usuario(usuario, clave, dsn=None):
    """¿Es esta la contrasena de este usuario? Para pedirla antes de cambiarla."""
    with _motor(dsn).connect() as cx:
        r = cx.execute(text("SELECT clave FROM usuarios WHERE usuario = :u AND activo"),
                       {"u": (usuario or "").strip().lower()}).scalar()
    return bool(r) and verifica(clave or "", r)

def de_testigo(testigo, dsn=None):
    """El usuario de una sesion viva, o None."""
    if not testigo:
        return None
    with _motor(dsn).connect() as cx:
        r = cx.execute(text(
            "SELECT u.id, u.usuario, u.nombre FROM sesiones s"
            " JOIN usuarios u ON u.id = s.usuario_id"
            " WHERE s.testigo = :t AND s.expira_en > now() AND u.activo"),
            {"t": _huella(testigo)}).mappings().first()
    return dict(r) if r else None

def sale(testigo, dsn=None):
    if not testigo:
        return False
    with _motor(dsn).begin() as cx:
        return bool(cx.execute(text("DELETE FROM sesiones WHERE testigo = :t"),
                               {"t": _huella(testigo)}).rowcount)

def limpia_sesiones(dsn=None):
    with _motor(dsn).begin() as cx:
        return cx.execute(text("DELETE FROM sesiones WHERE expira_en < now()")).rowcount
